name: 自动更新
on:
 workflow_dispatch: null
 schedule:
  - cron: 0 16 * * *
permissions:
 contents: write
concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true
jobs:
 zdgx:
  runs-on: ubuntu-latest
  steps:
   - name: 检出仓库
     uses: actions/checkout@v4
     with:
      fetch-depth: 0
      token: ${{ secrets.pat }}
   - name: 设置 Git 远程为 PAT 授权
     run: |
      git remote set-url origin https://fabaonb:${{ secrets.pat }}@github.com/fabaonb/3xui.git
   - name: 配置 Git 用户信息
     run: |
      git config --global user.name "github-actions[bot]"
      git config --global user.email "github-actions[bot]@users.noreply.github.com"
   - name: 备份 main.yml 文件
     run: cp .github/workflows/main.yml /tmp/main.yml
   - name: 删除 .github 目录下除 workflows 外的所有内容
     run: |
      find .github -mindepth 1 ! -path ".github/workflows" ! -path ".github/workflows/*" -exec rm -rf {} +
   - name: 删除 workflows 中除 main.yml 外的所有内容
     run: |
      find .github/workflows/ -mindepth 1 ! -name 'main.yml' -exec rm -rf {} +
   - name: 提交并推送清理后的内容
     run: |
      git add .
      git commit --allow-empty-message -m "" || true
      git push origin main --force
   - name: 添加上游仓库并获取最新代码
     run: |
      git remote add upstream https://github.com/MHSanaei/3x-ui.git
      git fetch upstream
   - name: 强制同步上游 main 分支
     run: git reset --hard upstream/main
   - name: 还原 main.yml 到 workflows
     run: |
      mkdir -p .github/workflows
      cp /tmp/main.yml .github/workflows/main.yml
   - name: 提交 main.yml 更改
     run: |
      git add .github/workflows/main.yml
      git commit --allow-empty-message -m "" || true
      git push origin main --force
   - name: 删除 .github 目录下除 workflows 外的所有内容
     run: |
      find .github -mindepth 1 ! -path ".github/workflows" ! -path ".github/workflows/*" -exec rm -rf {} +
   - name: 删除 workflows 中除 main.yml 外的所有内容
     run: |
      find .github/workflows/ -mindepth 1 ! -name 'main.yml' -exec rm -rf {} +
   - name: 提交并推送清理后的内容
     run: |
      git add .
      git commit --allow-empty-message -m "" || true
      git push origin main --force
